feat(core): expose loaded plugins
hawtio/hawtio-core pull request #46
Opened 2021-09-22 05:07 UTC by brusdev

The loaded plugins include the context path required to get plugin resources, i.e. AcriveMQ Artemis clould use the loaded plugins to avoid reloading them: https://github.com/apache/activemq-artemis/pull/3765

2021-09-22 05:25 UTC, oscerd approved these changes

2021-09-22 05:36 UTC, tadayosi requested changes
Hmm, I still don't get why we need this. The PluginServlet and PluginRegistry in hawtio/hawtio are what we provide for users and other plugins.

2021-09-22 07:14 UTC, brusdev commented
@tadayosi indeed the current ActiveMQ Artemis branding plugin use PluginServlet to get the plugin list, see https://github.com/apache/activemq-artemis/blob/main/artemis-hawtio/activemq-branding/src/main/webapp/plugin/js/brandingPlugin.js#L37

When a user accesses the console the PluginServlet is requested twice the first time from hawtio PluginLoader and the second time from ActiveMQ Artemis branding plugin.

**This is change is just to avoid the second request of PluginServlet from ActiveMQ Artemis branding plugin** and reuse the outcome of the first request of PluginServlet from hawtio PluginLoader.

2021-09-24 01:42 UTC, tadayosi approved these changes

2021-09-24 01:45 UTC, tadayosi commented
@brusdev Thanks. It makes sense. It shouldn't be harmful to have the plugins loaded from hawtioPluginLoader accessible from outside.

2021-09-24 01:45 UTC, merged